name = "DLMReader"
uuid = "e1d33f9a-7203-49d2-8e1a-e3c4f85197b8"
authors = ["sl-solution <github.sl.solution@icloud.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
